default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  port: 5432
  host: localhost

# development:
#  adapter: postgresql
#  encoding: utf8
#  database: mydb
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: postgres
#  password: 123456
#  port: 5432
#  host: localhost

development:
  adapter: postgresql
  encoding: utf8
  database: recovery_2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dhkjtcjkpwnxvr
  password: 123456
  port: 5432
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: jamboninja_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  port: 5432
  host: localhost

  production: &TEST
    adapter: postgresql
    encoding: utf8
    database: jamboninja_production
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# production:
#  adapter: postgresql
#  encoding: utf8
#  database: mydb
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: guilhermenunes09
#  password: 123456
#  port: 5432
#  host: localhost

cucumber:
  <<: *TEST
