development:
 adapter: postgresql
 encoding: utf8
 database: jamboninja_development
 pool: 5
 username:
 password:

test: &TEST
 adapter: postgresql
 encoding: utf8
 database: jamboninja_test
 pool: 5
 username:
 password:

production: &TEST
 adapter: postgresql
 encoding: utf8
 database: jamboninja_production
 pool: 5
 username:
 password:

cucumber:
 <<: *TEST

